#ifndef SOLVER_IBM_VERSION_HPP
#define SOLVER_IBM_VERSION_HPP

// Authoritative release version, shared by C++, Windows resources and packaging.
// Solver-IBM is an altered version of FluidX3D; preserve the upstream attribution.
#define SOLVER_IBM_VERSION_MAJOR 1
#define SOLVER_IBM_VERSION_MINOR 1
#define SOLVER_IBM_VERSION_PATCH 0
#define SOLVER_IBM_RELEASE_STATUS "development"

#define SOLVER_IBM_STRINGIFY_IMPL(value) #value
#define SOLVER_IBM_STRINGIFY(value) SOLVER_IBM_STRINGIFY_IMPL(value)
#define SOLVER_IBM_VERSION_STRING SOLVER_IBM_STRINGIFY(SOLVER_IBM_VERSION_MAJOR) "." SOLVER_IBM_STRINGIFY(SOLVER_IBM_VERSION_MINOR) "." SOLVER_IBM_STRINGIFY(SOLVER_IBM_VERSION_PATCH)
#define SOLVER_IBM_VERSION_RESOURCE SOLVER_IBM_VERSION_MAJOR,SOLVER_IBM_VERSION_MINOR,SOLVER_IBM_VERSION_PATCH,0
#define SOLVER_IBM_NAME "Solver-IBM"
#define SOLVER_IBM_EXECUTABLE "Solver-IBM.exe"
#define SOLVER_IBM_UPSTREAM_NAME "FluidX3D"
#define SOLVER_IBM_UPSTREAM_VERSION "3.8"
#define SOLVER_IBM_UPSTREAM_CREDIT "Copyright (c) Dr. Moritz Lehmann"

#endif
